apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-helm
  namespace: argocd
spec:
  project: default
  source:
    chart: helm-guestbook
    repoURL: https://github.com/shivaji-wsa/argo-project
    targetRevision: 0.1.1
    helm:
      releaseName: sealed-secrets
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
